[package]
name = "niftysubs"
version = "0.0.0"
authors = [ "Vasile Vlaicu <niftyrexnft@gmail.com>",]
edition = "2018"
publish = false

[lib]
path = "src/niftysubs_main.rs"

[dependencies.elrond-wasm]
version = "0.36.1"

[dev-dependencies.elrond-wasm-debug]
version = "0.36.1"
